# -*- coding: utf-8 -*-
"""WebScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQWhm8ThRiAnsD2r0-l2HTbLWDoUWuX3
"""

# import libraries

from bs4 import BeautifulSoup
import requests
import time
import datetime

import smtplib

url='https://www.amazon.in/dp/B0BDHX8Z63?tag=googmantxtmob55-21&ascsubtag=_k_CjwKCAjwq4imBhBQEiwA9Nx1Bv-bAQH5gzCrGChL52tmZIQDNngOVUBaFR0PaVtY7NlYXojpomuNjxoCBYAQAvD_BwE_k_&gclid=CjwKCAjwq4imBhBQEiwA9Nx1Bv-bAQH5gzCrGChL52tmZIQDNngOVUBaFR0PaVtY7NlYXojpomuNjxoCBYAQAvD_BwE'

headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}

page=requests.get(url)


soup1= BeautifulSoup(page.content,'html.parser')

soup2= BeautifulSoup(soup1.prettify(),'html.parser')

title= soup2.find( id ="productTitle").getText()

price_dollar = soup2.find(name="span", class_="a-price-whole").getText()
price_cents = soup2.find(name="span", class_="a-price-fraction").getText()
total_price = (float(f"{price_dollar}{price_cents}"))

total_price=total_price.strip()[1:]
title=title.strip

print(title)
print(total_price)
#type(price)

import datetime
today=datetime.date.today()
print(today)

import csv
header=['Title','Price','Date']
data= [title,total_price,today]
#type(data) --- list

with open('AmazonWebDataset.csv','w',newline='',encoding='UTF8')as f:
  writer=csv.writer(f)    # creating a csv file
  writer.writerow(header) # adding the heading
  writer.writerow(data)   # adding the data

import pandas as pd
df=pd.read_csv('C:\Users\hp\AmazonWebDataset.csv')
print(df)

#Now we are appending the data to the csv

with open('AmazonWebDataset.csv','a+',newline='',encoding='UTF8')as f:
  writer=csv.writer(f)    # creating a csv file
  writer.writerow(data)   # adding the data

#to check the price chance or not
def check_price():

  url='https://www.amazon.com/Funny-Data-Systems-Business-Analyst/dp/B07FNW9FGJ/ref=sr_1_3?dchild=1&keywords=data%2Banalyst%2Btshirt&qid=1626655184&sr=8-3&customId=B0752XJYNL&th=1'

  headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"}

  page=requests.get(url)

  soup1= BeautifulSoup(page.content,'html.parser')

  soup2= BeautifulSoup(soup1.prettify(),'html.parser')

  title= soup2.find( id ="productTitle").getText()

  price_dollar = soup2.find(name="span", class_="a-price-whole").getText()
  price_cents = soup2.find(name="span", class_="a-price-fraction").getText()
  total_price = (float(f"{price_dollar}{price_cents}"))

  total_price=total_price.strip()[1:]
  title=title.strip

  import datetime

  today=datetime.date.today()

  import csv
  header=['Title','Price','Date']
  data= [title,total_price,today]

  with open('AmazonWebDataset.csv','a+',newline='',encoding='UTF8')as f:
      writer=csv.writer(f)    # creating a csv file
      writer.writerow(data)   # adding the data

#checking after the specific time this case is 3600 sec means like every hour sec lets suppose
while(True):
  check_price()
  time.sleep(3600)

#appending the data after every check
with open('AmazonWebDataset.csv','a+',newline='',encoding='UTF8')as f:
  writer=csv.writer(f)    # creating a csv file
  writer.writerow(data)   # adding the data